### ISSUE TITLE
Automated tests for styx

### ISSUE THREAD

**Issue by gabestein** [underlay/underworld#10]

**Comment by joeltg** [comment]
This got a major refactor in [this pr](https://github.com/underlay/styx/pull/5) but I'm leaving it open until the LUBM queries have automated benchmarks, which is still a big priority.

**Comment by joeltg** [comment]
The LUBM tests are now split off into their [own repo](https://github.com/underlay/styx-lubm) that has a much better build process for everything (good enough to call "automated"). The next goal in performance evaluating Styx is going to require generating random subgraphs of the data, which will can be its own project and issue.
