### ISSUE TITLE
REST package server implementation

### ISSUE THREAD

**Issue by isTravis** [underlay/underworld#11]
- GET/PUT messages, packages, files
- Specify namespace

**Comment by metasj** [comment]
[Messages spec](https://github.com/underlay/overview/blob/master/MESSAGES.md) 

[Packages spec](https://github.com/underlay/overview/blob/master/PACKAGES.md)  -- design meeting 12/5?

**Comment by joeltg** [comment]
pkgs now has minimum viable functionality that includes

- GET/HEAD (packages, messages, files)
- PUT (messages, files)
- MKCOL (packages)
- DELETE (packages, messages, files)

all documented in its [README.md](https://github.com/underlay/pkgs/blob/master/README.md).

Future development and features will be tracked in other issues, starting with #12 and #13
