### ISSUE TITLE
Specify messages and packages

### ISSUE THREAD

**Issue by gabestein** [underlay/underworld#8]

**Comment by joeltg** [comment]
- [Messages](https://github.com/underlay/overview/blob/master/MESSAGES.md) in 4d106ae2189695e45c3570d6ae165fdcedc717c6
- [Packages](https://github.com/underlay/overview/blob/master/PACKAGES.md) in a2c736d001a2bbca4c0144d91b8d2e3fef413f44

Both are still evolving drafts
